version: '3'
services:

  #PHP7 Service
  php7:
    build: ./php7
    container_name: php7
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php7
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./webroot:/var/www/html
      - ./php7/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webroot:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - php7
    networks:
      app-network:
        aliases:
          - api.localhost

  #MySQL Service
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: mysqltemp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - app-network

  #PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    tty: true
    ports:
      - "9001:80"
    environment:
      PMA_HOST: mysql
    networks:
      - app-network

  #Swagger Editor Service
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "9002:8080"
    networks:
      - app-network

  #Swagger UI Service
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "9003:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    networks:
      - app-network

  #API Sprout Service
  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "swagger-api"
    ports:
      - "9004:8000"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    command: /openapi.json
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
