version: '3'
services:

  #PHP Service
  app:
    build: ./php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./webroot:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webroot:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: mysqltemp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - app-network

  #PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    tty: true
    ports:
      - "9001:80"
    environment:
      PMA_HOST: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
